### ISSUE TITLE
multiprocessing.pool.MaybeEncodingError

### ISSUE THREAD

**Issue by Cactusolo** [marekborowiec/AMAS#11]
Hi,
I have a alignment with 7902 seqs, when I'm running cms as `AMAS.py summary -f fasta -i ./Clade.fasta -d dna -c 8 -o Clade_summary.txt` with any threads >2, then it gaves me err as below:

```
Traceback (most recent call last):
  File "/home/cactus/miniconda3/bin/AMAS.py", line 10, in <module>
    sys.exit(main())
  File "/home/cactus/miniconda3/lib/python3.7/site-packages/amas/AMAS.py", line 1982, in main
    meta_aln = MetaAlignment(**kwargs)
  File "/home/cactus/miniconda3/lib/python3.7/site-packages/amas/AMAS.py", line 1039, in __init__
    self.alignment_objects = self.get_alignment_objects()
  File "/home/cactus/miniconda3/lib/python3.7/site-packages/amas/AMAS.py", line 1354, in get_alignment_objects
    alignments = pool.map(self.get_alignment_object, self.in_files)
  File "/home/cactus/miniconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/cactus/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<amas.AMAS.DNAAlignment object at 0x2b6421bdcba8>]'. Reason: 'error("'i' format requires -2147483648 <= number <= 2147483647")'
```

Please help!

Miao

**Comment by marekborowiec** [comment]
Because AMAS cannot spread computing of summaries on a single file over multiple processes, specifying multiple cores for this task does not make sense. I am not sure what this error of multiprocessing is, but you shouldn't be using multiple cores here anyways.
