### ISSUE TITLE
AMAS just broke

### ISSUE THREAD

**Issue by bioinfowheat** [marekborowiec/AMAS#13]
Hello,

I love AMAS for my phylogenomics projects. I've had it running for 2 years, and I just realized that it broke sometime over the last month. This is true for several installations, as well as a fresh one. Not sure if I screwed up a dependency in Python3 or not ... I'm running latest Python .... that might be it, not sure.

here's the error I get running on Linux (Debian)

Traceback (most recent call last):
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 2017, in <module>
    main()
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 1985, in main
    meta_aln.write_summaries(kwargs["summary_out"])
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 1514, in write_summaries
    summary_out = self.get_summaries()
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 1452, in get_summaries
    summaries = [alignment.get_summary() for alignment in alignments]
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 1452, in <listcomp>
    summaries = [alignment.get_summary() for alignment in alignments]
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 953, in get_summary
    data = self.summarize_alignment()
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 706, in summarize_alignment
    self.no_missing_ambiguous = self.get_sites_no_missing_ambiguous()
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 784, in get_sites_no_missing_ambiguous
    no_missing_ambiguous_sites = [self.get_site_no_missing_ambiguous(column) for column in range(self.get_alignment_length())]                                                                            
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 784, in <listcomp>
    no_missing_ambiguous_sites = [self.get_site_no_missing_ambiguous(column) for column in range(self.get_alignment_length())]                                                                            
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 788, in get_site_no_missing_ambiguous
    site = self.get_column(column)
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 776, in get_column
    return [row[i] for row in self.matrix]
  File "/mnt/griffin/chrwhe/software/AMAS/amas/AMAS.py", line 776, in <listcomp>
    return [row[i] for row in self.matrix]
IndexError: list index out of range

**Comment by marekborowiec** [comment]
This could be any number of things. Feel free to email me with your data file and I can see if I can make it run.
